# Generated by Django 5.2.7 on 2025-10-19 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdl_number', models.CharField(help_text="Commercial Driver's License number", max_length=50, unique=True)),
                ('dot_number', models.CharField(blank=True, help_text='DOT number', max_length=50, null=True)),
                ('phone_number', models.CharField(help_text="Driver's phone number", max_length=20)),
                ('assigned_vehicle', models.CharField(blank=True, help_text='Currently assigned vehicle', max_length=100, null=True)),
                ('home_terminal_address', models.CharField(help_text="Driver's home terminal address", max_length=500)),
                ('time_zone', models.CharField(default='America/New_York', help_text="Driver's home terminal time zone", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
            },
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(choices=[('off-duty', 'Off Duty'), ('sleeper-berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on-duty-not-driving', 'On Duty (Not Driving)')], help_text='Current duty status of the driver', max_length=50)),
                ('current_location', models.CharField(help_text="Driver's current location (address or coordinates)", max_length=500)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Current location latitude', max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Current location longitude', max_digits=10, null=True)),
                ('pickup_location', models.CharField(blank=True, help_text='Pickup location for the trip', max_length=500, null=True)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Pickup location latitude', max_digits=10, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Pickup location longitude', max_digits=10, null=True)),
                ('dropoff_location', models.CharField(blank=True, help_text='Dropoff location for the trip', max_length=500, null=True)),
                ('dropoff_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Dropoff location latitude', max_digits=10, null=True)),
                ('dropoff_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Dropoff location longitude', max_digits=10, null=True)),
                ('start_time', models.DateTimeField(help_text='Start time of the activity')),
                ('end_time', models.DateTimeField(blank=True, help_text='End time of the activity (null if ongoing)', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes for on-duty status', null=True)),
                ('odometer_reading', models.IntegerField(blank=True, help_text='Vehicle odometer reading at time of log', null=True)),
                ('engine_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Engine hours at time of log', max_digits=8, null=True)),
                ('vehicle_id', models.CharField(blank=True, help_text='Vehicle identification number or license plate', max_length=100, null=True)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Hours used in current duty cycle', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this log entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this log entry was last updated')),
                ('is_edited', models.BooleanField(default=False, help_text='Whether this log has been edited after creation')),
                ('edit_reason', models.TextField(blank=True, help_text='Reason for editing this log entry', null=True)),
                ('driver', models.ForeignKey(help_text='Driver associated with this log entry', on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ELD Log',
                'verbose_name_plural': 'ELD Logs',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['driver', 'start_time'], name='routes_eldl_driver__1b8245_idx'), models.Index(fields=['activity_status'], name='routes_eldl_activit_4b3139_idx'), models.Index(fields=['created_at'], name='routes_eldl_created_fb0c16_idx')],
            },
        ),
    ]
